//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelComment
    {
        public int id { get; set; }
        public int hotelId { get; set; }
        public string text { get; set; }
        public string author { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
