//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public Tour()
        {
            this.Type = new HashSet<Type>();
        }
    
        public int id { get; set; }
        public int ticketsCount { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte[] imagePreview { get; set; }
        public decimal price { get; set; }
        public bool isActual { get; set; }
        public string countryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Type> Type { get; set; }
    }
}
